# Generated by Django 6.0.6 on 2026-07-20 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_channel_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('uploads_playlist_id', models.CharField(max_length=100)),
                ('encrypted_refresh_token', models.TextField()),
                ('granted_scopes', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('REAUTH_REQUIRED', 'Reauthorization required')], db_index=True, default='CONNECTED', max_length=30)),
                ('subscriber_count', models.PositiveBigIntegerField(default=0)),
                ('video_count', models.PositiveBigIntegerField(default=0)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_channel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeChannelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('videos_analyzed', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.JSONField(default=dict)),
                ('top_videos', models.JSONField(default=list)),
                ('weak_videos', models.JSONField(default=list)),
                ('content_gaps', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('raw_metrics', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='youtube_channels.youtubechannel')),
            ],
        ),
    ]
