"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os 
import sys
from datetime import timedelta
import dj_database_url

from dotenv import load_dotenv

load_dotenv() 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-ty9+kkt1l$39@-kul@_p@=t_#--nt+jjyd6pc4!@y22u_bi$g%',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'categories',
    'ideas',
    'users',
    'youtube_channels',
    'billing',
]

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.LoggingJWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'core.exceptions.api_exception_handler',
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "ideas.performance": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# CORS configuration — allows the frontend (Lovable, mobile, etc.) to call
# this API from a browser. Origins are env-driven so preview domains can be
# added without code changes. CorsMiddleware intercepts OPTIONS preflight
# requests and returns 200 with CORS headers BEFORE DRF's auth/permission
# layer runs, so preflight requests never hit the 401 auth wall.
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        'CORS_ALLOWED_ORIGINS',
        'https://creatorintent.com,https://www.creatorintent.com,https://creator-intent.lovable.app',
    ).split(',')
    if origin.strip()
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    pattern.strip()
    for pattern in os.getenv(
        'CORS_ALLOWED_ORIGIN_REGEXES',
        (
            r'^http://localhost:\d+$,'
            r'^http://127\.0\.0\.1:\d+$,'
            r'^https://[a-z0-9-]+\.lovable\.app$,'
            r'^https://[a-z0-9-]+\.vercel\.app$'
        ),
    ).split(',')
    if pattern.strip()
]
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'Authorization']
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    db_url = os.getenv('DATABASE_URL') or os.getenv('database_url')
    if db_url:
        DATABASES = {
            'default': dj_database_url.config(
                default=db_url,
                conn_max_age=600,
                conn_health_checks=True,
            )
        }
    else:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('DB_NAME'),
                'USER': os.getenv('DB_USER'),
                'PASSWORD': os.getenv('DB_PASS'),
                'HOST': os.getenv('DB_HOST'),
                'PORT': os.getenv('DB_PORT'),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

YOUTUBE_API_KEY = os.getenv('YOUTUBE_API_KEY', '')
YOUTUBE_OAUTH_REDIRECT_URI = os.getenv('YOUTUBE_OAUTH_REDIRECT_URI', '')
FRONTEND_YOUTUBE_REDIRECT_URL = os.getenv('FRONTEND_YOUTUBE_REDIRECT_URL', '')
YOUTUBE_TOKEN_ENCRYPTION_KEY = os.getenv('YOUTUBE_TOKEN_ENCRYPTION_KEY', '')
YOUTUBE_ANALYSIS_DAYS = int(os.getenv('YOUTUBE_ANALYSIS_DAYS', '90'))
YOUTUBE_ANALYSIS_MAX_VIDEOS = int(os.getenv('YOUTUBE_ANALYSIS_MAX_VIDEOS', '30'))
YOUTUBE_ANALYSIS_MIN_VIDEOS = int(os.getenv('YOUTUBE_ANALYSIS_MIN_VIDEOS', '10'))
YOUTUBE_ANALYSIS_REFRESH_MINUTES = int(
    os.getenv('YOUTUBE_ANALYSIS_REFRESH_MINUTES', '60')
)
IDEA_EXPIRY_HOURS = int(os.getenv('IDEA_EXPIRY_HOURS', '26'))
IDEA_CRON_SECRET = os.getenv('IDEA_CRON_SECRET', '')
IDEA_CRON_MAX_ATTEMPTS = int(os.getenv('IDEA_CRON_MAX_ATTEMPTS', '3'))
IDEA_CRON_RETRY_BASE_SECONDS = float(
    os.getenv('IDEA_CRON_RETRY_BASE_SECONDS', '5')
)
IDEA_CRON_RETRY_MAX_SECONDS = float(
    os.getenv('IDEA_CRON_RETRY_MAX_SECONDS', '30')
)
DEEPSEEK_API_KEY = os.getenv('DEEPSEEK_API_KEY', '')
DEEPSEEK_MODEL = os.getenv('DEEPSEEK_MODEL', 'deepseek-v4-flash')
DEEPSEEK_TIMEOUT_SECONDS = int(os.getenv('DEEPSEEK_TIMEOUT_SECONDS', '60'))
GROQ_API_KEY = os.getenv('GROQ_API_KEY', '')
GROQ_MODEL = os.getenv('GROQ_MODEL', 'openai/gpt-oss-120b')
GROQ_TIMEOUT_SECONDS = int(os.getenv('GROQ_TIMEOUT_SECONDS', '60'))
GROQ_REASONING_EFFORT = os.getenv('GROQ_REASONING_EFFORT', 'low')
GROQ_MAX_COMPLETION_TOKENS = int(
    os.getenv('GROQ_MAX_COMPLETION_TOKENS', '2048')
)
GROQ_RATE_LIMIT_RETRIES = int(os.getenv('GROQ_RATE_LIMIT_RETRIES', '1'))
GROQ_MAX_RETRY_WAIT_SECONDS = float(
    os.getenv('GROQ_MAX_RETRY_WAIT_SECONDS', '30')
)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_IMAGE_MODEL = os.getenv('OPENAI_IMAGE_MODEL', 'gpt-image-2')
OPENAI_IMAGE_SIZE = os.getenv('OPENAI_IMAGE_SIZE', '1536x1024')
OPENAI_IMAGE_QUALITY = os.getenv('OPENAI_IMAGE_QUALITY', 'low')
OPENAI_IMAGE_OUTPUT_FORMAT = os.getenv('OPENAI_IMAGE_OUTPUT_FORMAT', 'png')
OPENAI_TIMEOUT_SECONDS = int(os.getenv('OPENAI_TIMEOUT_SECONDS', '120'))
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME', '')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY', '')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET', '')
CLOUDINARY_TIMEOUT_SECONDS = int(os.getenv('CLOUDINARY_TIMEOUT_SECONDS', '60'))

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TASK_IGNORE_RESULT = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_TIMEOUT = 5
CELERY_TASK_PUBLISH_RETRY = False
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv('CELERY_TASK_SOFT_TIME_LIMIT', '420'))
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '450'))
CONTENT_PACKAGE_JOB_STALE_SECONDS = int(
    os.getenv('CONTENT_PACKAGE_JOB_STALE_SECONDS', '600')
)

# Lemon Squeezy billing integration
LEMON_SQUEEZY_API_KEY = os.getenv('LEMON_SQUEEZY_API_KEY', '')
LEMON_SQUEEZY_WEBHOOK_SECRET = os.getenv('LEMON_SQUEEZY_WEBHOOK_SECRET', '')
LEMON_SQUEEZY_STORE_ID = os.getenv('LEMON_SQUEEZY_STORE_ID', '')
LEMON_SQUEEZY_API_BASE_URL = os.getenv(
    'LEMON_SQUEEZY_API_BASE_URL', 'https://api.lemonsqueezy.com/v1'
)
LEMON_SQUEEZY_TIMEOUT_SECONDS = int(os.getenv('LEMON_SQUEEZY_TIMEOUT_SECONDS', '30'))
FRONTEND_BILLING_SUCCESS_URL = os.getenv('FRONTEND_BILLING_SUCCESS_URL', '')
MOBILE_BILLING_SUCCESS_URL = os.getenv('MOBILE_BILLING_SUCCESS_URL', '')
