# Generated by Django 6.0.6 on 2026-07-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_regions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='negative_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='search_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='category',
            name='youtube_category_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
