# Generated by Django 6.0.6 on 2026-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_default_regions_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='youtube_category_titles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
