# Generated by Django 6.0.6 on 2026-09-12 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtube_channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NichePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube_data_api', max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(default='none', max_length=100)),
                ('calculation_version', models.CharField(default='v1', max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('evidence_mode', models.CharField(choices=[('EVIDENCE_BACKED', 'Evidence-backed opportunity'), ('LIMITED_EVIDENCE', 'Early opportunity'), ('AI_FALLBACK', 'AI-suggested idea')], default='AI_FALLBACK', max_length=30)),
                ('identity', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('last_search_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_requested_at', models.DateTimeField(blank=True, null=True)),
                ('web_context', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube_data_api', max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('youtube_channel_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('uploads_playlist_id', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChannelDNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube_data_api', max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(default='none', max_length=100)),
                ('calculation_version', models.CharField(default='v1', max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('evidence_mode', models.CharField(choices=[('EVIDENCE_BACKED', 'Evidence-backed opportunity'), ('LIMITED_EVIDENCE', 'Early opportunity'), ('AI_FALLBACK', 'AI-suggested idea')], default='AI_FALLBACK', max_length=30)),
                ('profile', models.JSONField(default=dict)),
                ('performance_summary', models.JSONField(default=dict)),
                ('confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('refresh_requested_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dna', to='youtube_channels.youtubechannel')),
                ('niche_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_profiles', to='intelligence.nichepool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube_data_api', max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(default='none', max_length=100)),
                ('calculation_version', models.CharField(default='v1', max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('evidence_mode', models.CharField(choices=[('EVIDENCE_BACKED', 'Evidence-backed opportunity'), ('LIMITED_EVIDENCE', 'Early opportunity'), ('AI_FALLBACK', 'AI-suggested idea')], default='AI_FALLBACK', max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_ideas', to='intelligence.channeldna')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotaLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('search_calls', models.PositiveIntegerField(default=0)),
                ('data_units', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quota_entries', to='intelligence.nichepool')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube_data_api', max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('youtube_video_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('format', models.CharField(default='unknown', max_length=20)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('like_count', models.PositiveBigIntegerField(default=0)),
                ('comment_count', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='intelligence.publicchannel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoStatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube_data_api', max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('like_count', models.PositiveBigIntegerField(default=0)),
                ('comment_count', models.PositiveBigIntegerField(default=0)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='intelligence.youtubevideo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdeaEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube_data_api', max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='intelligence.generatedidea')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.publicchannel')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intelligence.youtubevideo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NichePoolChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube_data_api', max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(default='none', max_length=100)),
                ('calculation_version', models.CharField(default='v1', max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('evidence_mode', models.CharField(choices=[('EVIDENCE_BACKED', 'Evidence-backed opportunity'), ('LIMITED_EVIDENCE', 'Early opportunity'), ('AI_FALLBACK', 'AI-suggested idea')], default='AI_FALLBACK', max_length=30)),
                ('relevant', models.BooleanField(default=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='intelligence.nichepool')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='intelligence.publicchannel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pool', 'channel'), name='unique_niche_channel')],
            },
        ),
        migrations.CreateModel(
            name='CompetitorBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube_data_api', max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(default='none', max_length=100)),
                ('calculation_version', models.CharField(default='v1', max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('evidence_mode', models.CharField(choices=[('EVIDENCE_BACKED', 'Evidence-backed opportunity'), ('LIMITED_EVIDENCE', 'Early opportunity'), ('AI_FALLBACK', 'AI-suggested idea')], default='AI_FALLBACK', max_length=30)),
                ('format', models.CharField(max_length=20)),
                ('age_bucket', models.CharField(max_length=30)),
                ('median_views', models.FloatField(default=0)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='intelligence.publicchannel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('channel', 'format', 'age_bucket'), name='unique_competitor_baseline')],
            },
        ),
        migrations.CreateModel(
            name='TrendSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='youtube_data_api', max_length=100)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('model_version', models.CharField(default='none', max_length=100)),
                ('calculation_version', models.CharField(default='v1', max_length=100)),
                ('confidence', models.FloatField(default=0)),
                ('evidence_mode', models.CharField(choices=[('EVIDENCE_BACKED', 'Evidence-backed opportunity'), ('LIMITED_EVIDENCE', 'Early opportunity'), ('AI_FALLBACK', 'AI-suggested idea')], default='AI_FALLBACK', max_length=30)),
                ('outlier_multiplier', models.FloatField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='intelligence.nichepool')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='intelligence.youtubevideo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pool', 'video'), name='unique_pool_video_signal')],
            },
        ),
    ]
