# Generated by Django 6.0.6 on 2026-09-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nichepool',
            name='collection_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
