# Generated by Django 6.0.6 on 2026-09-23 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_add_collection_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorIdeaFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_key', models.CharField(blank=True, max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('next_refresh_at', models.DateTimeField(blank=True, null=True)),
                ('dna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idea_feed', to='intelligence.channeldna')),
            ],
        ),
    ]
