# Generated by Django 6.0.6 on 2026-07-05 10:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_category_default_regions_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('region_code', models.CharField(db_index=True, default='GLOBAL_EN', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('why_now', models.TextField()),
                ('audience_promise', models.TextField()),
                ('suggested_format', models.CharField(max_length=80)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('freshness', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=20)),
                ('trend_score', models.PositiveSmallIntegerField(default=0)),
                ('source_signal', models.CharField(blank=True, max_length=255)),
                ('source_video_count', models.PositiveIntegerField(default=0)),
                ('evidence_video_ids', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_candidates', to='categories.category')),
            ],
            options={
                'ordering': ['-trend_score', '-generated_at'],
                'indexes': [models.Index(fields=['category', 'region_code', 'is_active'], name='ideas_ideac_categor_5c6853_idx'), models.Index(fields=['category', 'region_code', '-trend_score'], name='ideas_ideac_categor_3d17ff_idx'), models.Index(fields=['batch_id'], name='ideas_ideac_batch_i_9765d4_idx')],
            },
        ),
    ]
