# Generated by Django 6.0.6 on 2026-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideacandidate',
            name='region_code',
            field=models.CharField(db_index=True, default='US', max_length=20),
        ),
    ]
